# Welcome to Adriano J. Holanda Projects!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adriano J. Holanda Projects
email: ajholanda@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the repository for projects where the availability
  of data, source code, graphics, graphs and other materials
  becomes important for the understanding of the concepts and
  the reproducibility and test of the experiments.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://holanda.xyz" # the base hostname & protocol for your site
twitter_username: ajholanda
github_username:  ajholanda

# Build settings
markdown: kramdown
