# Welcome to Adriano J. Holanda pages!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adriano J. Holanda pages
email: ajholanda@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the repository for additional documentation of the projects
  stored in github where the availability
  of data set, source code, graphics, graphs and other materials
  becomes important for the understanding of the concepts and
  the reproducibility and test of the experiments performed.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ajholanda.github.io" # the base hostname & protocol for your site
github_username:  ajholanda

# Build settings
markdown: kramdown
